{{- range .Values.databases }}
{{- if .backup.enabled }}
{{- $db := . }}
{{- $strategy := .backup.strategy }}

{{- /* Full Backup CronJob */ -}}
{{- if and $strategy $strategy.full $strategy.full.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}-backup-full
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}-backup
    backup-type: full
spec:
  schedule: {{ $strategy.full.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .name }}-backup
            backup-type: full
        spec:
          serviceAccountName: {{ .backup.serviceAccount.name | default (printf "%s-backup-sa" .name) }}
          restartPolicy: OnFailure
          containers:
          - name: mssql-backup-full
            image: "{{ .backup.image.repository }}:{{ .backup.image.tag }}"
            imagePullPolicy: {{ .backup.image.pullPolicy }}
            command: ["/bin/bash", "-c"]
            args:
              - |
                set -eo pipefail
                source /opt/mssql/scripts/aws-credentials.sh
                /opt/mssql/scripts/backup-full.sh
            env:
              - name: MSSQL_SA_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .secretName }}
                    key: {{ .secretKey }}
              - name: DB_SERVER
                value: "{{ .name }}-svc"
              - name: DB_DATABASE
                value: "{{ .database }}"
              - name: S3_BUCKET
                value: "{{ .backup.s3Bucket }}"
              - name: S3_REGION
                value: "{{ .backup.s3Region }}"
{{- end }}

{{- /* Differential Backup CronJob */ -}}
{{- if and $strategy $strategy.differential $strategy.differential.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}-backup-differential
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}-backup
    backup-type: differential
spec:
  schedule: {{ $strategy.differential.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .name }}-backup
            backup-type: differential
        spec:
          serviceAccountName: {{ .backup.serviceAccount.name | default (printf "%s-backup-sa" .name) }}
          restartPolicy: OnFailure
          containers:
          - name: mssql-backup-differential
            image: "{{ .backup.image.repository }}:{{ .backup.image.tag }}"
            imagePullPolicy: {{ .backup.image.pullPolicy }}
            command: ["/bin/bash", "-c"]
            args:
              - |
                set -eo pipefail
                source /opt/mssql/scripts/aws-credentials.sh
                /opt/mssql/scripts/backup-differential.sh
            env:
              - name: MSSQL_SA_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .secretName }}
                    key: {{ .secretKey }}
              - name: DB_SERVER
                value: "{{ .name }}-svc"
              - name: DB_DATABASE
                value: "{{ .database }}"
              - name: S3_BUCKET
                value: "{{ .backup.s3Bucket }}"
              - name: S3_REGION
                value: "{{ .backup.s3Region }}"
{{- end }}

{{- /* Transaction Log Backup CronJob */ -}}
{{- if and $strategy $strategy.log $strategy.log.enabled }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}-backup-log
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}-backup
    backup-type: log
spec:
  schedule: {{ $strategy.log.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ .name }}-backup
            backup-type: log
        spec:
          serviceAccountName: {{ .backup.serviceAccount.name | default (printf "%s-backup-sa" .name) }}
          restartPolicy: OnFailure
          containers:
          - name: mssql-backup-log
            image: "{{ .backup.image.repository }}:{{ .backup.image.tag }}"
            imagePullPolicy: {{ .backup.image.pullPolicy }}
            command: ["/bin/bash", "-c"]
            args:
              - |
                set -eo pipefail
                source /opt/mssql/scripts/aws-credentials.sh
                /opt/mssql/scripts/backup-log.sh
            env:
              - name: MSSQL_SA_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .secretName }}
                    key: {{ .secretKey }}
              - name: DB_SERVER
                value: "{{ .name }}-svc"
              - name: DB_DATABASE
                value: "{{ .database }}"
              - name: S3_BUCKET
                value: "{{ .backup.s3Bucket }}"
              - name: S3_REGION
                value: "{{ .backup.s3Region }}"
{{- end }}

{{- end }}
{{- end }}