{{ $ := . -}}
{{- range .Values.databases }}
{{- if .externalSecrets }}
{{- range .externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ .secretStore }}
    kind: ClusterSecretStore
  refreshInterval: "1m"
  target:
    name: {{ .name }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .secretName }}
{{- end }}
{{- end }}
{{- end }}
