{{- range .Values.databases }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-svc
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-name: "my-shared-mssql-nlb"
spec:
  type: LoadBalancer
  selector:
    app: {{ .name }}
  ports:
    - port: {{ .port }}
      targetPort: 1433
      protocol: TCP
{{- end }}
