{{- if .Values.cloudflare.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
type: Opaque
stringData:
  api-token: {{ .Values.secrets.cloudflareToken }}
{{- end }}
---
{{- if .Values.aws.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: prod-route53-credentials-secret
type: Opaque
stringData:
  secret-access-key: {{ .Values.secrets.awsSecret }}
{{- end -}}
