apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
{{ include "mongo.labels" . | indent 4 }}
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "mongo.labels" . | indent 6 }}
  serviceName: mongo
  template:
    metadata:
      name: mongo
      labels:
{{ include "mongo.labels" . | indent 8 }}
    spec:
      containers:
      - image: "{{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}"
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        resources:
          {{- toYaml .Values.mongo.resources | nindent 10 }}
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.mongo.pvc.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  annotations:
    {{- toYaml .Values.pritunl.service.annotations | nindent 4 }}
  labels:
{{ include "mongo.labels" . | indent 4 }}
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
  {{ range $index, $port := .Values.mongo.service.ports }}
  - name: {{ $port.name }}
    port: {{ $port.value }}
    targetPort: {{ $port.value }}
    protocol: TCP
  {{ end }}
  selector:
    app: mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongo.pvc.name }}
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.pvc.request.storage }}
