apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pritunl.fullname" . }}
  labels:
{{ include "pritunl.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pritunl.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: pritunl
  template:
    metadata:
      labels:
{{ include "pritunl.labels" . | indent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.pritunl.image.repository }}:{{ .Values.pritunl.image.tag }}"
          imagePullPolicy: {{ .Values.pritunl.image.pullPolicy }}
          env:
            {{ toYaml .Values.pritunl.service.environment | nindent 12 }}
          ports:
          {{ range $index, $port := .Values.pritunl.service.ports }}
            - containerPort: {{ $port.value }}
              protocol: TCP
          {{ end }}
          resources:
            {{- toYaml .Values.pritunl.resources | nindent 12 }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: pritunl-persistent-storage
              mountPath: /var/lib/pritunl
      volumes:
        - name: pritunl-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Values.pritunl.pvc.name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: pritunl
  annotations:
    {{- toYaml .Values.pritunl.service.annotations | nindent 4 }}
  labels:
    {{ include "pritunl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pritunl.service.type }}
  ports:
  {{ range $index, $port := .Values.pritunl.service.ports }}
  - name: {{ $port.name }}
    port: {{ $port.value }}
    targetPort: {{ $port.value }}
    protocol: {{ $port.protocol }}
  {{ end }}
  selector:
    app: pritunl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pritunl.pvc.name }}
  labels:
    app: pritunl
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pritunl.pvc.request.storage }}
