apiVersion: v1
kind: Service
metadata:
  name: pritunl-ui
  namespace: pritunl
  annotations:
    {{- toYaml .Values.pritunlUi.service.annotations | nindent 4 }}
  labels:
{{ include "pritunlUi.labels" . | indent 4 }}
spec:
  type: {{ .Values.pritunlUi.service.type }}
  ports:
  {{ range $index, $port := .Values.pritunlUi.service.ports }}
  - name: {{ $port.name }}
    port: {{ $port.value }}
    targetPort: {{ $port.value }}
    protocol: TCP
  {{ end }}
  selector:
    app: pritunl
---
{{- if .Values.pritunlUi.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pritunl-ui
  labels:
{{ include "pritunl.labels" . | indent 4 }}
  {{- with .Values.pritunlUi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.pritunlUi.ingress.tls }}
  tls:
  {{- range .Values.pritunlUi.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.pritunlUi.ingress.hosts }}
  {{ $svcPort := .port }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: pritunl-ui
                port: 
                  number: {{ $svcPort }}
        {{- end }}
  {{- end }}
{{- end }}
