apiVersion: v2
name: pritunl
home: https://pritunl.com/
version: 0.3.2
appVersion: v1.32.3897.75
description: Enterprise Distributed OpenVPN and IPsec Server
icon: https://pritunl.com/img/pritunl_onelogin_square.png
sources:
- https://github.com/pritunl/pritunl
