apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
    {{- toYaml .Values.service.labels | nindent 4 }}
spec:
  template:
    metadata:
      annotations:
{{ toYaml .Values.service.annotations | nindent 8 }}
    spec:
      containerConcurrency: 1
      containers:
      - args:
          {{- if .Values.extraArgs }}
          {{ toYaml .Values.extraArgs | indent 10 }}
          {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          {{- toYaml .Values.ports | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
          {{- if .Values.volumeMounts }}
          {{ toYaml .Values.volumeMounts | indent 10}}
          {{- end }} 
      serviceAccountName: {{ include "serviceAccountName" . }}
      timeoutSeconds: 3600
      volumes:
        {{- if .Values.volumes }}
        {{ toYaml .Values.volumes | indent 8 }}
        {{- end }}
        

  traffic:
  - latestRevision: true
    percent: 100