apiVersion: v2
name: monitoring
description: Helm chart for Prometheus
type: application
version: 0.1.0
dependencies:
- name: kube-prometheus-stack
  version: 44.2.1
  appVersion: v0.62.0
  repository: https://prometheus-community.github.io/helm-charts
- name: version-checker
  appVersion: v0.2.1
  version: 0.2.3
  repository: https://ymrsmns.github.io/helm-charts