kube-prometheus-stack:
  grafana:
    enabled: false
  defaultRules:
    create: false
  alertmanager:
    enabled: false
  prometheus:
    prometheusSpec:
      resources:
        requests:
          memory: 1Gi
        limits:
          memory: 1Gi
      remoteWrite:
        - url: https://mimir-CLIENT_NAME.prod.cloudkite.io/api/v1/push
          basicAuth:
            username:
              name: basic-auth-creds
              key: username
            password:
              name: basic-auth-creds
              key: password
          headers:
            X-Scope-OrgID: CLIENT_NAME
          writeRelabelConfigs:
            - sourceLabels:
              - "__name__"
              regex: "kubernetes_build_info|version_checker_is_latest_version"
              action: "keep"
          queueConfig:
            capacity: 5000
            maxSamplesPerSend: 1000
            maxShards: 100
      externalLabels:
        cluster: CLUSTER_NAME
      image:
          registry: quay.io
          repository: prometheus/prometheus
          tag: v2.45.0
  prometheusOperator:
    verticalPodAutoscaler:
      enabled: true

# basic_auth:
#   username: USERNAME
#   password: PASSWORD

version-checker:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: "monitoring"

vpaApps:
  monitoring-kube-state-metrics:
    kind: Deployment
    mode: Auto
    minReplicas: 1
  monitoring-prometheus-node-exporter:
    kind: DaemonSet
    mode: Auto
    minReplicas: 2
  version-checker:
    kind: Deployment
    mode: Auto
    minReplicas: 1
  prometheus-monitoring-kube-prometheus-prometheus:
    kind: StatefulSet
    mode: Auto
    minReplicas: 1

loki:
  # Configures the readiness probe for all of the Loki pod
  image:
    # -- The Docker registry
    registry: docker.io
    # -- Docker image repository
    repository: grafana/loki
    # -- Overrides the image tag whose default is the chart's appVersion
    # TODO: needed for 3rd target backend functionality
    # revert to null or latest once this behavior is relased
    tag: null
    # -- Overrides the image tag with an image digest
    digest: null
    # -- Docker image pull policy
    pullPolicy: IfNotPresent
  # -- Common annotations for all deployments/StatefulSets
  annotations: {}
  # -- Common annotations for all pods
  podAnnotations: {}
  # -- Common labels for all pods
  podLabels: {}
  configStorageType: ConfigMap
  # -- Name of the Secret or ConfigMap that contains the configuration (used for naming even if config is internal).
  externalConfigSecretName: '{{ include "loki.name" . }}'
  # -- Config file contents for Loki
  # @default -- See values.yaml
  config: |

    {{- with .Values.loki.server }}
    server:
      {{- toYaml . | nindent 2}}
    {{- end}}

    memberlist:
    {{- if .Values.loki.memberlistConfig }}
      {{- toYaml .Values.loki.memberlistConfig | nindent 2 }}
    {{- else }}
    {{- if .Values.loki.extraMemberlistConfig}}
    {{- toYaml .Values.loki.extraMemberlistConfig | nindent 2}}
    {{- end }}
      join_members:
        - {{ include "loki.memberlist" . }}
        {{- with .Values.migrate.fromDistributed }}
        {{- if .enabled }}
        - {{ .memberlistService }}
        {{- end }}
        {{- end }}
    {{- end }}
