apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-cluster-secret-store
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.clusterSecretStore.projectID }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.clusterSecretStore.clusterLocation }}
          clusterName: {{ .Values.clusterSecretStore.clusterName }}
          serviceAccountRef: 
            name: {{ $.Release.Name }}
            namespace: {{ $.Release.Name }}
