loadBalancerName: mssql-load-balancer

# Global image configuration
image:
  repository: gcr.io/cloudkite-public/mssql
  tag: "2022"
  pullPolicy: IfNotPresent

databases:
  - name: db-a
    database: db_a
    port: 1433
    storage: 50Gi
    secretName: db-a-db-secret
    secretKey: sa-password
    edition: Developer
    loadBalancerName: mssql-lb # this is used in case the default exceeds the 32 character limit
    externalSecrets:
      - name: db-secret
        secretName: kubernetes/stage-eks/db-secret
        secretStore: aws-secret-manager
    initSql: |
      CREATE DATABASE another_db;
      GO;
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        memory: 4Gi
  - name: db-b
    database: db_b
    port: 1433
    storage: 50Gi
    secretName: db-b-db-secret
    secretKey: sa-password
    edition: Developer
    loadBalancerName: staging-lb
    image:
      repository: gcr.io/cloudkite-public/mssql
      tag: "2019"
      pullPolicy: IfNotPresent
    initSql: |
      CREATE DATABASE another_db;
      GO;
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        memory: 4Gi
