apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-admission-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpa-admission-controller
  template:
    metadata:
      labels:
        app: vpa-admission-controller
    spec:
      serviceAccountName: vpa-admission-controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      containers:
        - name: admission-controller
          image: "{{ .Values.admissionController.image.repository }}:{{ .Values.admissionController.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.admissionController.image.pullPolicy }}
          args:
          {{- if .Values.admissionController.tlsCertArgs }}
            {{- toYaml .Values.admissionController.tlsCertArgs | nindent 12 }}
          {{- end }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            {{- toYaml .Values.admissionController.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.admissionController.resources | nindent 12 }}
          ports:
            - containerPort: 8000
            - name: prometheus
              containerPort: 8944
      {{- with .Values.admissionController.volumes }}
      volumes:
      {{- toYaml . | nindent 8 }}
      {{- end }}
