apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-admission-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpa-admission-controller
  template:
    metadata:
      labels:
        app: vpa-admission-controller
    spec:
      serviceAccountName: vpa-admission-controller
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      containers:
        - name: admission-controller
          image: "{{ .Values.admissionController.image.repository }}:{{ .Values.admissionController.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.admissionController.image.pullPolicy }}
          {{- if .Values.admissionController.command }}
          command:
            {{- toYaml .Values.admissionController.command | nindent 12 }}
          {{- end }}
          {{- if .Values.admissionController.args }}
          args:
            {{- toYaml .Values.admissionController.args | nindent 12 }}
          {{- end }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            {{- with .Values.admissionController.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{ end }}
          resources:
            {{- toYaml .Values.admissionController.resources | nindent 12 }}
          ports:
            - containerPort: 8000
            - name: prometheus
              containerPort: 8944
      volumes:
        - name: tls-certs
          secret:
            secretName: vpa-tls-certs
        {{- with .Values.admissionController.volumes }}
        {{- toYaml . | nindent 8 }}
        {{ end }}
