apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vpa-cert
spec:
  dnsNames:
    - vpa-webhook.kube-system.svc
  secretName: vpa-tls-certs
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  issuerRef:
    kind: Issuer
    name: vpa-ca-issuer
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vpa-selfsigned-ca-cert
spec:
  isCA: true
  commonName: vpa-ca
  secretName: vpa-ca-root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: cluster-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io