apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.selfSignedCert.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  secretName: {{ .Values.selfSignedCert.secretName }}
  issuerRef:
    name: {{ .Values.selfSignedCert.issuer }}
    kind: Issuer
  dnsNames:
    {{- toYaml .Values.selfSignedCert.hosts | nindent 4 }}
