{{- if .Values.basic_auth }}
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-creds
data:
  username: {{ .Values.basic_auth.username | b64enc }}
  password: {{ .Values.basic_auth.password | b64enc }}
{{- end }}