{{- range $vpaAppName, $vpaAppConfig := .Values.vpaApps }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ if eq $vpaAppName "prometheus" }}{{ $vpaAppName }}-{{ $.Chart.Name }}-{{ $vpaAppName }}{{ else }}{{ $.Chart.Name }}-{{ $vpaAppName }}{{- end }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind:       {{ $vpaAppConfig.kind }}
    name:       {{ if eq $vpaAppName "prometheus" }}{{ $vpaAppName }}-{{ $.Chart.Name }}-{{ $vpaAppName }}{{ else }}{{ $.Chart.Name }}-{{ $vpaAppName }}{{- end }}
  updatePolicy:
    updateMode: {{ $vpaAppConfig.mode | default "Auto" }}
    minReplicas: {{ $vpaAppConfig.minReplicas | default "1" }}
---
{{- end }}