apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tailscale.fullname" . }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "tailscale.fullname" .  }}
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
