{{- if .Values.authKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tailscale.fullname" . }}
  namespace: {{ .Release.Namespace }}
stringData:
  TS_AUTH_KEY: {{ .Values.authKey }}
{{- end }}
