prometheusRule:
- name: default-groups
  groups:
    - name: nginx_ingress
      rules:
        - alert: NGINXTooMany500s
          expr: '100 * ( sum( nginx_ingress_controller_requests{status=~"5.+"} ) / sum(nginx_ingress_controller_requests) ) > 5'
          for: 5m
          labels:
            severity: warning
          annotations:
            description: Too many 5XXs
            summary: More than 5% of all requests returned 5XX, this requires your attention

    - name: kubernetes_apps
      rules:
        - alert: KubePodCrashLooping
          annotations:
            description: Pod stuck in crashbackloop
          expr: 'rate(kube_pod_container_status_restarts_total{job="kube-state-metrics"}[15m]) * 60 * 5 > 0'
          for: 1h
          labels:
            severity: warning

    - name: kubernetes_jobs
      rules:
        - alert: KubernetesJobFailed
          expr: 'kube_job_status_failed > 5'
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: Kubernetes Job failed
            description: "Job"

    - name: solr_cloud
      rules:
        - alert: SolrCloudLowLiveNodeCount
          annotations:
            summary: Solr low live node count
            description: "Solr has less than two live nodes for replica"
          expr: 'solr_collections_live_nodes > 2'
          for: 5m
          labels:
            severity: warning
            instance: solr

    - name: velero
      rules:
        - alert: VeleroBackupFailures
          expr: 'velero_backup_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25'
          for: 30m
          labels:
            severity: warning
          annotations:
            description: Velero backup failure
            summary: Velero backup has failed backups.
