apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}
  annotations: 
    {{ range $key, $value := .Values.serviceAccount.annotations -}}
      {{ $key }}: {{ $value }}
    {{- end -}}