{{ range $hpaAppName, $hpaAppConfig := .Values.hpaApps }}
{{- if $hpaAppConfig.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $hpaAppName }}-hpa
  labels:
    app: {{ $hpaAppName }}
    product: {{ $.Release.Name }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  maxReplicas: {{ $hpaAppConfig.maxReplicas }}
  minReplicas: {{ $hpaAppConfig.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $hpaAppName }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ $hpaAppConfig.memoryTarget }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $hpaAppConfig.cpuTarget }}
---
{{- end }}
{{- end }}