{{- if .Values.kubernetes.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubernetes-rules
spec:
  groups:
    - name: kubernetes_apps
      rules:
        - alert: KubePodCrashLooping
          annotations:
            description: 'Pod {{ "{{" }} $labels.namespace }}/{{ "{{" }} $labels.pod }} ({{ "{{" }} $labels.container }}) is restarting {{ "{{" }} printf "%.2f" $value }} times / 5 minutes.'
          expr: 'rate(kube_pod_container_status_restarts_total{job="kube-state-metrics"}[15m]) * 60 * 5 > 5'
          for: 30m
          labels:
            severity: warning
    - name: kubernetes_jobs
      rules:
        - alert: KubernetesJobFailed
          expr: 'kube_job_status_failed > 2'
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: 'Job {{ "{{" }} $labels.namespace }}/{{ "{{" }} $labels.job_name }} failed to complete.'
            description: "Job"

    - name: kubernetes-storage
      rules:
        - alert: KubePersistentVolumeUsageCritical
          annotations:
            description: 'The PersistentVolume claimed by {{ "{{" }} $labels.persistentvolumeclaim }} in Namespace {{ "{{" }} $labels.namespace }} is only {{ "{{" }} printf "%0.2f" $value }}% free.'
          expr: '100 * kubelet_volume_stats_available_bytes{job="kubelet"}/kubelet_volume_stats_capacity_bytes{job="kubelet"} < 3'
          for: 10m
          labels:
            severity: critical
        - alert: KubePersistentVolumeFullInFourDays
          annotations:
            description: 'Based on recent sampling, the PersistentVolume claimed by {{ "{{" }} $labels.persistentvolumeclaim }} in Namespace {{ "{{" }} $labels.namespace }} is expected to fill up within four days. Currently {{ "{{" }} printf "%0.2f" $value }}% is available.'
          expr: '100 * (kubelet_volume_stats_available_bytes{job="kubelet"}/kubelet_volume_stats_capacity_bytes{job="kubelet"}) < 15 and predict_linear(kubelet_volume_stats_available_bytes{job="kubelet"}[6h], 4 * 24 * 3600) < 0'
          for: 10m
          labels:
            severity: critical
        - alert: KubePersistentVolumeErrors
          annotations:
            description: 'The persistent volume {{ "{{" }} $labels.persistentvolume }} has status {{ "{{" }} $labels.phase }}.'
          expr: 'kube_persistentvolume_status_phase{phase=~"Failed|Pending",job="kube-state-metrics"} > 0'
          for: 10m
          labels:
            severity: critical

    - name: kube-prometheus-node-alerting.rules
      rules:
        - alert: NodeDiskRunningFull
          annotations:
            description: 'Device {{ "{{" }} $labels.device }} of node-exporter {{ "{{" }} $labels.namespace }}/{{ "{{" }} $labels.pod }} will be full within the next 24 hours.'
          expr: '(node:node_filesystem_usage: > 0.85) and (predict_linear(node:node_filesystem_avail:[6h], 3600 * 24) < 0)'
          for: 30m
          labels:
            severity: warning
        - alert: NodeDiskRunningFull
          annotations:
            description: 'Device {{ "{{" }} $labels.device }} of node-exporter {{ "{{" }} $labels.namespace }}/{{ "{{" }} $labels.pod }} will be full within the next 2 hours.'
          expr: '(node:node_filesystem_usage: > 0.85) and (predict_linear(node:node_filesystem_avail:[30m], 3600 * 2) < 0)'
          for: 10m
          labels:
            severity: critical
{{- end }}
