{{- if .Values.kubernetes.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubernetes-rules
spec:
  groups:
    - name: kubernetes_apps
      rules:
        - alert: KubePodCrashLooping
          annotations:
            description: 'Pod {{ "{{" }} $labels.namespace }}/{{ "{{" }} $labels.pod }} ({{ "{{" }} $labels.container }}) is restarting {{ "{{" }} printf "%.2f" $value }} times / 5 minutes.'
          expr: 'rate(kube_pod_container_status_restarts_total{job="kube-state-metrics"}[15m]) * 60 * 5 > 5'
          for: 30m
          labels:
            severity: warning
    - name: kubernetes_jobs
      rules:
        - alert: KubernetesJobFailed
          expr: 'kube_job_status_failed > 2'
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: 'Job {{ "{{" }} $labels.namespace }}/{{ "{{" }} $labels.job_name }} failed to complete.'
            description: "Job"
{{- end }}
