apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | toJson }}
  {{- end }}
