apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "name" . }}
webhooks:
- name: {{ include "name" . }}.{{ $.Values.namespace }}.svc
  matchPolicy: Equivalent
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: Ignore
  {{- with .Values.webhook.rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
  clientConfig:
    caBundle: {{ .Values.secrets.tls_crt}}
    service:
      namespace: {{ .Values.namespace }}
      name: {{ include "name" . }}
      path: /mutate/