apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.secrets.tls_crt}}
  tls.key: {{ .Values.secrets.tls_key}}

