image:
  repository: ""
  pullPolicy: Always
  tag: ""
extraArgs: []
namespace: knative-apps
createNamespace: true
service:
  labels:
    networking.knative.dev/visibility: cluster-local
  annotations:
    autoscaling.knative.dev/target-utilization-percentage: "100"
env: []
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  annotations:
    iam.gke.io/gcp-service-account: ""
ports: []
resources: