selfSignedCert:
  enabled: true
  name: vpa-cert-by-certmanager
  issuer: vpa-self-signer
  secretName: vpa-tls-certs
  hosts:
    - vpa-webhook.kube-system.svc
    - vpa-webhook.kube-system.svc.cluster.local

admissionController:
  # Requires certs to be generated and published as a secret to the cluster
  # See https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/admission-controller/gencerts.sh
  image:
    repository: registry.k8s.io/autoscaling/vpa-admission-controller
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.2.1"

  args: ["--v=4", "--stderrthreshold=info", "--reload-cert"]

  volumeMounts:
    - name: tls-certs
      mountPath: "/etc/tls-certs"
      readOnly: true
  volumes:
    - name: tls-certs
      projected:
        sources:
          - secret:
              name: vpa-tls-certs
              items:
                - key: ca.crt
                  path: caCert.pem
                - key: tls.crt
                  path: serverCert.pem
                - key: tls.key
                  path: serverKey.pem

  resources:
    limits:
      memory: 300Mi
    requests:
      cpu: 50m
      memory: 200Mi

recommender:
  image:
    repository: registry.k8s.io/autoscaling/vpa-recommender
    pullPolicy: IfNotPresent
    tag: "1.2.1"

  resources:
    limits:
      memory: 1000Mi
    requests:
      cpu: 50m
      memory: 800Mi

  tlsCertArgs: [ ]
  recommendPerformanceLevel: default

  volumeMounts: [ ]

  volumes: [ ]

updater:
  image:
    repository: registry.k8s.io/autoscaling/vpa-updater
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "1.2.1"

  resources:
    limits:
      memory: 1000Mi
    requests:
      cpu: 50m
      memory: 800Mi
