admissionController:
  image:
    repository: registry.k8s.io/autoscaling/vpa-admission-controller
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.13.0"

  resources:
    limits:
      memory: 300Mi
    requests:
      cpu: 50m
      memory: 200Mi

recommender:
  image:
    repository: registry.k8s.io/autoscaling/vpa-admission-controller
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.13.0"

  resources:
    limits:
      memory: 1000Mi
    requests:
      cpu: 50m
      memory: 800Mi

  performanceHigh:
    image:
      repository: registry.k8s.io/autoscaling/vpa-admission-controller
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "0.13.0"

    resources:
      limits:
        memory: 1000Mi
      requests:
        cpu: 50m
        memory: 800Mi

  performanceLow:
    image:
      repository: registry.k8s.io/autoscaling/vpa-admission-controller
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "0.13.0"

    resources:
      limits:
        memory: 1000Mi
      requests:
        cpu: 50m
        memory: 800Mi

updater:
  image:
    repository: registry.k8s.io/autoscaling/vpa-updater
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.13.0"

  resources:
    limits:
      memory: 1000Mi
    requests:
      cpu: 50m
      memory: 800Mi
