admissionController:
  image:
    repository: registry.k8s.io/autoscaling/vpa-admission-controller
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.13.0"

  resources:
    limits:
      memory: 300Mi
    requests:
      cpu: 50m
      memory: 200Mi

  tlsCertArgs: []
#    - "--client-ca-file=/etc/tls-certs/ca.crt"
#    - "--tls-cert-file=/etc/tls-certs/tls.crt"
#    - "--tls-private-key=/etc/tls-certs/tls.key"

  volumeMounts: []
  #    - name: tls-certs
  #      mountPath: "/etc/tls-certs"
  #      readOnly: true
  volumes: []
  #    - name: tls-certs
  #      secret:
  #        secretName: vpa-tls-certs

recommender:
  image:
    repository: registry.k8s.io/autoscaling/vpa-recommender
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.13.0"

  resources:
    limits:
      memory: 1000Mi
    requests:
      cpu: 50m
      memory: 800Mi

  tlsCertArgs: [ ]
  #    - "--client-ca-file=/etc/tls-certs/ca.crt"
  #    - "--tls-cert-file=/etc/tls-certs/tls.crt"
  #    - "--tls-private-key=/etc/tls-certs/tls.key"

  # it can be default, high or low
  recommendPerformanceLevel: default

  volumeMounts: [ ]
  #    - name: tls-certs
  #      mountPath: "/etc/tls-certs"
  #      readOnly: true

  volumes: [ ]
  #    - name: tls-certs
  #      secret:
  #        secretName: vpa-tls-certs

updater:
  image:
    repository: registry.k8s.io/autoscaling/vpa-updater
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.13.0"

  resources:
    limits:
      memory: 1000Mi
    requests:
      cpu: 50m
      memory: 800Mi
